export const ModalWindowConstants = {
  CONTACTS : "CONTACTS",
  LOADING: "LOADING",
  ADD_TO_CART: "ADD_TO_CART",
  PRODUCT_SETTINGS: "PRODUCT_SETTINGS_MODAL",
  REMOVE_FROM_CART: "REMOVE_FROM_CART_MODAL"
}