export const ProductsConstants = {
  GET_ALL: "PRODUCTS_GET_ALL",
  GET_MORE: "PRODUCTS_GET_MORE",
  GET: "PRODUCT_GET",
  CHANGE_PAGE: "PRODUCTS_CHANGE_PAGE",
  CLEAR_PRODUCTS: "PRODUCTS_CLEAR_PRODUCTS"
}